version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8000:80"
    volumes:
      - "db_volume:/var/lib/mysql"
    networks:
      - php_advanced
  app:
    #    image: "php:8.1-apache"
    build:
      context: .docker/
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    networks:
      - php_advanced