version: "3.8"

volumes:
  db_volumes:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    networks:
      - php_advanced


  php:
    #    image: "php:8.1-apache"
    build:
      context: .docker/
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - php_advanced
